#!/bin/bash

export PATH=/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/bin/:$PATH
cd ${redcap_phoenix}

#BSUB -q pri_pnl
#BSUB -o /data/predict/utility/bsub/redcap-import-%J-%I.out
#BSUB -e /data/predict/utility/bsub/redcap-import-%J-%I.err
#BSUB -n 4

i=`head -${LSB_JOBINDEX} ${redcap_records} | tail -1`

# this echo is for knowing which subject a .err file corresponds to
echo -e '\033[0;31m' $i '\033[0m' >&2

ls -la $i
/data/predict/utility/import_records_all.py $i $redcap_dict $API_TOKEN ${redcap_phoenix}/date_offset.csv $FORCE


