#!/bin/bash

source /data/pnl/soft/pnlpipe3/miniconda3/bin/activate
conda activate dpimport
cd ${redcap_phoenix}

#BSUB -q pri_pnl
#BSUB -o /data/predict/utility/bsub/redcap-import-%J-%I.out
#BSUB -e /data/predict/utility/bsub/redcap-import-%J-%I.err

i=`head -${LSB_JOBINDEX} ${redcap_records} | tail -1`

ls -la $i
# /data/predict/utility/import_records_all.py $i /data/predict/utility/yale-nh $API_TOKEN
# /data/predict/utility/import_records_all.py $i /data/predict/utility/amp-scz-form $API_TOKEN
# /data/predict/utility/import_records_all.py $i /data/predict/utility/redcap-ii-yale $API_TOKEN


