#!/bin/bash

NDA_ROOT=$1
cd $NDA_ROOT

# direct rsync of a big list generated by * fails
# so we generate the big list first and then rsync
list=$NDA_ROOT/.rsync_eegqc.list
rm -f $list && touch $list

# go into each site directory
for s in `ls -d */PHOENIX/PROTECTED/*/`
do
    # now go into each subject directory
    for d in `ls -d ${s}/processed/???????/`
    do
        # echo $d
        ls ${d}/eeg/*/Figures/*[!QC].png >> $list 2>/dev/null
        ls ${d}/eeg/*/Figures/*_runSheet.* >> $list 2>/dev/null
    done
done
# the nested for loops were required to prevent
# "ls: Argument list too long" within cron job

export LD_LIBRARY_PATH=/apps/software/librsync/2.3.4-GCCcore-13.3.0/lib:$LD_LIBRARY_PATH
export PATH=/apps/software/rsync/3.4.1-GCCcore-13.3.0/bin:$PATH
rsync -avR --files-from=$list . $2


