#!/bin/bash

NDA_ROOT=$1
cd $NDA_ROOT

# direct rsync of a big list generated by * fails
# so we generate the big list first and then rsync
list=$NDA_ROOT/.rsync_eegqc.list
rm -f $list && touch $list

for d in `ls -d */PHOENIX/PROTECTED/*/`
do
    ls ${d}/processed/*/eeg/*/Figures/*[!QC].png >> $list
    ls ${d}/processed/*/eeg/*/Figures/*_runSheet.* >> $list
done

rsync -avR --files-from=$list . rc-predict-gen.partners.org:$2


